title: Ivan Moreira - Strategic Project Manager & Digital Transformation Consultant
email: ivan@ivanmoreira.com
description: >-
  Strategic Project Manager & Digital Transformation Consultant helping organizations 
  navigate complex transformations with AI-enhanced methodologies and proven leadership strategies.
baseurl: ""
url: ""

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Collections
collections:
  services:
    output: true
    permalink: /:collection/:name/

# Include pages from _pages directory
include:
  - _pages

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "_pages"
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "_services"
      type: "services"
    values:
      layout: "service"

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - admin/

# Site data
author:
  name: Ivan Moreira
  email: ivan@ivanmoreira.com
  linkedin: https://linkedin.com/in/ivanmoreira
  twitter: https://twitter.com/ivanmoreiraconsulting

# SEO
twitter:
  username: ivanmoreiraconsulting
  card: summary_large_image

facebook:
  app_id: 
  publisher: 

social:
  name: Ivan Moreira
  links:
    - https://linkedin.com/in/ivanmoreira
    - https://twitter.com/ivanmoreiraconsulting

