# Site settings
title: Ivan Moreira
email: ivan@ivanmoreira.com
description: >-
  Strategic Project Manager & Digital Transformation Consultant.
  Helping organizations navigate complex transformations with AI-enhanced methodologies.
baseurl: ""
url: "https://ivanmoreira.com"

# Author information
author:
  name: Ivan Moreira
  email: ivan@ivanmoreira.com
  bio: Strategic Project Manager & Digital Transformation Consultant
  location: Global
  linkedin: ivanmoreira
  twitter: ivanmoreira

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/

# Collections
collections:
  services:
    output: true
    permalink: /services/:name/
  speaking:
    output: true
    permalink: /speaking/:name/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - admin/

# Sass configuration
sass:
  sass_dir: _sass
  style: compressed

# SEO settings
twitter:
  username: ivanmoreira
  card: summary_large_image

facebook:
  app_id: 
  publisher: 
  admins: 

social:
  name: Ivan Moreira
  links:
    - https://twitter.com/ivanmoreira
    - https://linkedin.com/in/ivanmoreira
    - https://github.com/ivanmoreira

# Google Analytics
google_analytics: 

# Contact form settings
contact:
  email: ivan@ivanmoreira.com
  phone: "+1 (555) 123-4567"
  address: "Global Remote Consulting"

# Navigation
navigation:
  - name: Home
    url: /
  - name: About
    url: /about/
  - name: Services
    url: /services/
  - name: Speaking
    url: /speaking/
  - name: Blog
    url: /blog/
  - name: Contact
    url: /contact/

# Footer links
footer_links:
  - name: Privacy Policy
    url: /privacy/
  - name: Terms of Service
    url: /terms/
  - name: Contact
    url: /contact/

# Theme settings
theme_color: "#007AFF"
background_color: "#FFFFFF"
text_color: "#1D1D1F"
accent_color: "#007AFF"

# Performance settings
compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

